/**
 * pdfExport.js
 * Monthly statement PDF export using jsPDF + autotable
 */
import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

export const exportToPDF = (transactions, summary, month) => {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })

  // Header
  doc.setFillColor(34, 197, 94)
  doc.rect(0, 0, 210, 30, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(22)
  doc.setFont('helvetica', 'bold')
  doc.text('MoneyFlow Statement', 105, 14, { align: 'center' })
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(`Period: ${month || 'All Time'}`, 105, 22, { align: 'center' })

  // Summary boxes
  doc.setTextColor(0, 0, 0)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')

  const boxY = 38
  // Balance box
  doc.setFillColor(240, 253, 244)
  doc.roundedRect(14, boxY, 55, 20, 3, 3, 'F')
  doc.setTextColor(21, 128, 61)
  doc.text('Balance', 41, boxY + 8, { align: 'center' })
  doc.setFontSize(13)
  doc.text(`Rs.${summary.balance.toFixed(0)}`, 41, boxY + 16, { align: 'center' })

  // Credit box
  doc.setFillColor(240, 253, 244)
  doc.roundedRect(77, boxY, 55, 20, 3, 3, 'F')
  doc.setTextColor(21, 128, 61)
  doc.setFontSize(11)
  doc.text('Total Credit', 104, boxY + 8, { align: 'center' })
  doc.setFontSize(13)
  doc.text(`Rs.${summary.totalCredit.toFixed(0)}`, 104, boxY + 16, { align: 'center' })

  // Debit box
  doc.setFillColor(255, 241, 242)
  doc.roundedRect(140, boxY, 56, 20, 3, 3, 'F')
  doc.setTextColor(159, 18, 57)
  doc.setFontSize(11)
  doc.text('Total Debit', 168, boxY + 8, { align: 'center' })
  doc.setFontSize(13)
  doc.text(`Rs.${summary.totalDebit.toFixed(0)}`, 168, boxY + 16, { align: 'center' })

  // Transactions table
  autoTable(doc, {
    startY: 68,
    head: [['Date', 'Description', 'Category', 'Account', 'Type', 'Need/Want', 'Amount (Rs.)']],
    body: transactions.map(t => [
      t.date,
      t.description,
      t.category,
      t.account,
      t.type === 'credit' ? 'Credit' : 'Debit',
      t.type === 'debit' ? (t.isWant ? 'Want' : 'Need') : '-',
      (t.type === 'credit' ? '+' : '-') + Number(t.amount).toFixed(0),
    ]),
    headStyles: { fillColor: [34, 197, 94], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    columnStyles: {
      0: { cellWidth: 22 },
      4: { fontStyle: 'bold' },
      6: { halign: 'right', fontStyle: 'bold' },
    },
    didDrawCell: (data) => {
      if (data.column.index === 6 && data.section === 'body') {
        const isCredit = data.row.raw[4] === 'Credit'
        doc.setTextColor(isCredit ? 21 : 159, isCredit ? 128 : 18, isCredit ? 61 : 57)
      }
    },
    margin: { left: 14, right: 14 },
  })

  // Footer
  const pageCount = doc.internal.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150)
    doc.text(`Generated by MoneyFlow | Page ${i} of ${pageCount}`, 105, 290, { align: 'center' })
  }

  doc.save(`MoneyFlow_Statement_${month || 'all'}.pdf`)
}
